# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('license_no', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('contact_no', models.BigIntegerField()),
                ('license_expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=30)),
                ('last_stoppage', models.CharField(max_length=30)),
                ('current_position', models.CharField(max_length=30)),
                ('distance_covered', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('license_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackingSystem.Driver')),
            ],
        ),
    ]
