# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.IntegerField(default=0),
        ),
    ]
