# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingSystem', '0003_auto_20180317_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrackingSystem.Vehicle'),
        ),
    ]
