# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingSystem', '0004_auto_20180404_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='buy_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='Anuj', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default='BMW', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
